### ISSUE TITLE
vue升级到3，并添加热更新

### ISSUE THREAD

**Issue by drc5521** [huangxubo23/tampermonkey-vue#1]
大佬能升级到vue3嘛，今天尝试到vue3，但是失败了，各种错误，还请大佬能升级vue3，并添加热更新。

**Comment by huangxubo23** [comment]
> 大佬能升级到vue3嘛，今天尝试到vue3，但是失败了，各种错误，还请大佬能升级vue3，并添加热更新。

已升级到Vue3，UI框架使用的Antd-Design-Vue，请查看`master`分支。

如果需要使用Vue2 + Element-UI，请查看`vue2.0`分支。

本地开发支持热更新，启动：
```
npm run dev
```
然后在浏览器访问：
```
http://localhost:8080/
```
